/**
 * Transcend Portal — Tournament Tiebreaker Fixtures & Default Data
 */

import {
  RankedTeamStanding,
  BracketSeedMatch,
} from "./tournament-tiebreaker-types";

export const DEFAULT_STANDINGS: RankedTeamStanding[] = [
  {
    rank: 1,
    seed: 1,
    team: {
      teamId: "team-chi",
      teamName: "Chicago Mission",
      division: "16U AAA",
      gamesPlayed: 4,
      wins: 4,
      losses: 0,
      ties: 0,
      otLosses: 0,
      points: 8,
      goalsFor: 18,
      goalsAgainst: 4,
      cappedGoalDifferential: 14,
      periodWins: 11,
      penaltyMinutes: 12,
      earliestGoalSeconds: 42,
    },
    tiebreakerReason: "Outright points leader (8 pts)",
    criterion: "POINTS",
  },
  {
    rank: 2,
    seed: 2,
    team: {
      teamId: "team-sjs",
      teamName: "San Jose Jr. Sharks AAA",
      division: "16U AAA",
      gamesPlayed: 4,
      wins: 3,
      losses: 1,
      ties: 0,
      otLosses: 0,
      points: 6,
      goalsFor: 15,
      goalsAgainst: 7,
      cappedGoalDifferential: 8,
      periodWins: 8,
      penaltyMinutes: 8,
      earliestGoalSeconds: 84,
    },
    tiebreakerReason: "Won head-to-head vs Shattuck (4-3)",
    criterion: "HEAD_TO_HEAD",
  },
  {
    rank: 3,
    seed: 3,
    team: {
      teamId: "team-ssm",
      teamName: "Shattuck St. Mary's",
      division: "16U AAA",
      gamesPlayed: 4,
      wins: 3,
      losses: 1,
      ties: 0,
      otLosses: 0,
      points: 6,
      goalsFor: 22,
      goalsAgainst: 8,
      cappedGoalDifferential: 10,
      periodWins: 9,
      penaltyMinutes: 14,
      earliestGoalSeconds: 55,
    },
    tiebreakerReason: "Lost head-to-head vs Jr. Sharks (3-4)",
    criterion: "HEAD_TO_HEAD",
  },
  {
    rank: 4,
    seed: 4,
    team: {
      teamId: "team-marlies",
      teamName: "Toronto Marlboros",
      division: "16U AAA",
      gamesPlayed: 4,
      wins: 2,
      losses: 1,
      ties: 1,
      otLosses: 0,
      points: 5,
      goalsFor: 12,
      goalsAgainst: 9,
      cappedGoalDifferential: 3,
      periodWins: 7,
      penaltyMinutes: 16,
      earliestGoalSeconds: 110,
    },
    tiebreakerReason: "Higher +/- 5 capped differential (+3 vs -1)",
    criterion: "GOAL_DIFFERENTIAL_CAP_5",
  },
  {
    rank: 5,
    seed: 5,
    team: {
      teamId: "team-honeybaked",
      teamName: "Detroit HoneyBaked",
      division: "16U AAA",
      gamesPlayed: 4,
      wins: 2,
      losses: 1,
      ties: 1,
      otLosses: 0,
      points: 5,
      goalsFor: 10,
      goalsAgainst: 11,
      cappedGoalDifferential: -1,
      periodWins: 6,
      penaltyMinutes: 10,
      earliestGoalSeconds: 145,
    },
    tiebreakerReason: "Lower capped differential (-1 vs +3)",
    criterion: "GOAL_DIFFERENTIAL_CAP_5",
  },
  {
    rank: 6,
    seed: 6,
    team: {
      teamId: "team-caesars",
      teamName: "Little Caesars",
      division: "16U AAA",
      gamesPlayed: 4,
      wins: 1,
      losses: 2,
      ties: 1,
      otLosses: 0,
      points: 3,
      goalsFor: 8,
      goalsAgainst: 12,
      cappedGoalDifferential: -4,
      periodWins: 5,
      penaltyMinutes: 6,
      earliestGoalSeconds: 210,
    },
    tiebreakerReason: "Fewest goals against in 3-way tie (12 GA)",
    criterion: "FEWEST_GOALS_AGAINST",
  },
  {
    rank: 7,
    seed: 7,
    team: {
      teamId: "team-blades",
      teamName: "MN Blades",
      division: "16U AAA",
      gamesPlayed: 4,
      wins: 1,
      losses: 2,
      ties: 1,
      otLosses: 0,
      points: 3,
      goalsFor: 9,
      goalsAgainst: 14,
      cappedGoalDifferential: -5,
      periodWins: 4,
      penaltyMinutes: 18,
      earliestGoalSeconds: 180,
    },
    tiebreakerReason: "Won period tiebreaker vs Boston (4 vs 2)",
    criterion: "PERIOD_WINS",
  },
  {
    rank: 8,
    seed: 8,
    team: {
      teamId: "team-eagles",
      teamName: "Boston Jr. Eagles",
      division: "16U AAA",
      gamesPlayed: 4,
      wins: 1,
      losses: 2,
      ties: 1,
      otLosses: 0,
      points: 3,
      goalsFor: 7,
      goalsAgainst: 16,
      cappedGoalDifferential: -7,
      periodWins: 2,
      penaltyMinutes: 20,
      earliestGoalSeconds: 310,
    },
    tiebreakerReason: "Final playoff qualifier (2 period wins)",
    criterion: "PERIOD_WINS",
  },
];

export const DEFAULT_BRACKET_SEEDS: BracketSeedMatch[] = [
  { seed1: 1, team1: "Chicago Mission", seed2: 8, team2: "Boston Jr. Eagles", round: "QUARTERFINALS", sheetName: "Sheet 1 (Main Arena)", scheduledTime: "Sun 08:00 AM" },
  { seed1: 4, team1: "Toronto Marlboros", seed2: 5, team2: "Detroit HoneyBaked", round: "QUARTERFINALS", sheetName: "Sheet 2 (South Rink)", scheduledTime: "Sun 08:30 AM" },
  { seed1: 2, team1: "San Jose Jr. Sharks AAA", seed2: 7, team2: "MN Blades", round: "QUARTERFINALS", sheetName: "Sheet 3 (West Arena)", scheduledTime: "Sun 09:45 AM" },
  { seed1: 3, team1: "Shattuck St. Mary's", seed2: 6, team2: "Little Caesars", round: "QUARTERFINALS", sheetName: "Sheet 4 (Olympic)", scheduledTime: "Sun 10:15 AM" },
];
